name: Deploy to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Insert AdSense + Analytics code
        run: |
          ADSENSE_CODE="${{ secrets.ADSENSE_CODE }}"
          ANALYTICS_CODE="${{ secrets.ANALYTICS_CODE }}"

          for file in $(find ./ -name "*.html"); do
            sed -i "s|<!-- ADSENSE_CODE -->|$ADSENSE_CODE|" "$file"
            sed -i "s|<!-- ANALYTICS_CODE -->|$ANALYTICS_CODE|" "$file"
          done

      - name: Clear FTP Directory
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "${{ secrets.FTP_TARGET_DIR }}"
          dangerous-clean-slate: true

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: "${{ secrets.FTP_TARGET_DIR }}"
